package com.service.service_2025;

import java.util.Arrays;
import java.util.List;

public class Data {
    List<String> places = Arrays.asList(
            "New York",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "San Francisco",
            "Columbus",
            "Indianapolis",
            "Seattle",
            "Denver",
            "Washington",
            "Boston",
            "Nashville",
            "Baltimore",
            "Louisville",
            "Portland",
            "Oklahoma City",
            "Milwaukee",
            "Las Vegas",
            "Albuquerque",
            "Tucson",
            "Fresno",
            "Sacramento",
            "Kansas City",
            "Mesa",
            "Atlanta",
            "Omaha",
            "Raleigh",
            "Miami",
            "Cleveland",
            "Tulsa",
            "Oakland",
            "Minneapolis",
            "Wichita",
            "Arlington",
            "Bakersfield",
            "Tampa",
            "Honolulu",
            "Anaheim",
            "Aurora",
            "Santa Ana",
            "St. Louis",
            "Riverside"
    );

    List<String> items = Arrays.asList(
            "T-shirt",
            "Jeans",
            "Sneakers",
            "Handbag",
            "Sunglasses",
            "Watch",
            "Perfume",
            "Laptop",
            "Smartphone",
            "Headphones",
            "Book",
            "Necklace",
            "Scarf",
            "Jacket",
            "Dress",
            "Apple",
            "Banana",
            "Milk",
            "Bread",
            "Eggs",
            "Cheese",
            "Chicken",
            "Rice",
            "Pasta",
            "Cereal",
            "Tomato",
            "Lettuce",
            "Olive Oil",
            "Coffee",
            "Sugar",
            "Hammer",
            "Screwdriver",
            "Wrench",
            "Nails",
            "Screws",
            "Drill",
            "Paint",
            "Paintbrush",
            "Tape Measure",
            "Ladder",
            "Pliers",
            "Sandpaper",
            "Light Bulb",
            "Extension Cord",
            "Toolbox",
            "Glue",
            "Duct Tape",
            "Broom",
            "Bucket",
            "Flashlight"
    );

    List<String> books = Arrays.asList(
            "To Kill a Mockingbird",
            "1984",
            "Pride and Prejudice",
            "The Great Gatsby",
            "The Catcher in the Rye",
            "Lord of the Rings",
            "Animal Farm",
            "The Hobbit",
            "Brave New World",
            "The Grapes of Wrath",
            "Moby-Dick",
            "War and Peace",
            "The Odyssey",
            "Crime and Punishment",
            "The Divine Comedy",
            "Jane Eyre",
            "Wuthering Heights",
            "The Scarlet Letter",
            "Great Expectations",
            "A Tale of Two Cities",
            "Don Quixote",
            "Les Misérables",
            "The Brothers Karamazov",
            "Ulysses",
            "Catch-22",
            "Lolita",
            "The Bell Jar",
            "Slaughterhouse-Five",
            "Fahrenheit 451",
            "One Hundred Years of Solitude",
            "Beloved",
            "The Handmaid's Tale",
            "Invisible Man",
            "The Color Purple",
            "A Clockwork Orange",
            "Their Eyes Were Watching God",
            "The Sun Also Rises",
            "Dune",
            "The Road",
            "The Stranger",
            "Frankenstein",
            "Dracula",
            "The Picture of Dorian Gray",
            "Charlotte's Web",
            "The Chronicles of Narnia",
            "Harry Potter and the Sorcerer's Stone",
            "The Alchemist",
            "The Kite Runner",
            "Life of Pi",
            "The Fault in Our Stars"
    );
}
